language: python
python:
  - "3.5"
os:
  - linux
dist: trusty
sudo: required
env:
  global:
    - SOLC_BASE_INSTALL_PATH=$TRAVIS_BUILD_DIR
matrix:
  include:
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e flake8"
    # installation
    - python: "2.7"
      env: TOX_POSARGS="-e py27-installation"
    - python: "3.4"
      env: TOX_POSARGS="-e py34-installation"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-installation"
    # solc 0.4.1
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.1
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.1
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.1
    # solc 0.4.2
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.2
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.2
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.2
    # solc 0.4.6
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.6
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.6
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.6
    # solc 0.4.7
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.7
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.7
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.7
    # solc 0.4.8
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.8
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.8
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.8
    # solc 0.4.9
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.9
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.9
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.9
    # solc 0.4.11
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.11
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.11
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.11
    # solc 0.4.12
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.12
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.12
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.12
    # solc 0.4.13
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.13
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.13
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.13
    # solc 0.4.14
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.14
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.14
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.14
    # solc 0.4.15
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.15
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.15
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.15
    # solc 0.4.16
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.16
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.16
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.16
    # solc 0.4.17
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.17
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.17
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.17
    # solc 0.4.18
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.18
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.18
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.18
    # solc 0.4.19
    - python: "2.7"
      env: TOX_POSARGS="-e py27" SOLC_VERSION=v0.4.19
    - python: "3.4"
      env: TOX_POSARGS="-e py34" SOLC_VERSION=v0.4.19
    - python: "3.5"
      env: TOX_POSARGS="-e py35" SOLC_VERSION=v0.4.19
cache:
  - pip: true
before_install:
install:
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
  - pip --version
  - pip install -e .  # install py-solc globally in order to use the solc installation scripts.
before_script:
  - python --version
  - if [ -n "$SOLC_VERSION" ]; then python -m solc.install $SOLC_VERSION; fi
  - if [ -n "$SOLC_VERSION" ]; then export SOLC_BINARY="$SOLC_BASE_INSTALL_PATH/solc-$SOLC_VERSION/bin/solc"; fi
  - if [ -n "$SOLC_VERSION" ]; then export LD_LIBRARY_PATH="$SOLC_BASE_INSTALL_PATH/solc-$SOLC_VERSION/bin"; fi
  - env
  - if [ -n "$SOLC_BINARY" ]; then $SOLC_BINARY --version; fi
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
